# Generated by Django 5.2.17 on 2026-09-02 01:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bill_number", models.CharField(max_length=20, unique=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("IN_STORE", "In-store"), ("ECOMMERCE", "E-commerce")],
                        default="IN_STORE",
                        max_length=20,
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[("CASH", "Cash"), ("UPI", "UPI"), ("CARD", "Card")],
                        max_length=20,
                    ),
                ),
                ("taxable_value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("gst_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SKU",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sku_code",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "barcode",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("color", models.CharField(max_length=60)),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("metre", "Metre"),
                            ("piece", "Piece"),
                            ("set", "Set"),
                            ("dozen", "Dozen"),
                            ("kg", "Kilogram"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("mrp", models.DecimalField(decimal_places=2, max_digits=10)),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("dynamic_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "safety_stock_threshold",
                    models.DecimalField(decimal_places=2, default=6, max_digits=10),
                ),
                ("rack", models.CharField(blank=True, max_length=20)),
                (
                    "parent_roll_id",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("is_online_enabled", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ItemType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                (
                    "default_unit_type",
                    models.CharField(
                        choices=[
                            ("metre", "Metre"),
                            ("piece", "Piece"),
                            ("set", "Set"),
                            ("dozen", "Dozen"),
                            ("kg", "Kilogram"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=160)),
                ("hsn_code", models.CharField(blank=True, max_length=15)),
                (
                    "gst_rate",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=4),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("lead_time_days", models.PositiveIntegerField(default=5)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InventoryBalance",
            fields=[
                (
                    "sku",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="balance",
                        serialize=False,
                        to="laxmi_backend.sku",
                    ),
                ),
                (
                    "physical_stock",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "reserved_online",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "damaged_qty",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                ("last_sale_at", models.DateTimeField(blank=True, null=True)),
                ("last_purchase_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="BillItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=10)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unit_cost_snapshot",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="laxmi_backend.bill",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bill_items",
                        to="laxmi_backend.sku",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("fabric", models.CharField(blank=True, max_length=80)),
                (
                    "item_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="brands",
                        to="laxmi_backend.itemtype",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("item_type", "name")},
            },
        ),
        migrations.AddField(
            model_name="sku",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="skus",
                to="laxmi_backend.product",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="laxmi_backend.brand",
            ),
        ),
        migrations.CreateModel(
            name="StaffUser",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin / Owner"),
                            ("BILLING", "Billing Counter"),
                            ("WAREHOUSE", "Warehouse Staff"),
                            ("PACKAGING", "Packaging / Dispatch"),
                        ],
                        default="BILLING",
                        max_length=20,
                    ),
                ),
                ("pin_hash", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InventoryLedger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("OPENING", "Opening stock"),
                            ("PURCHASE_RECEIVE", "Purchase received"),
                            ("PURCHASE_REJECT", "Purchase rejected (RCV)"),
                            ("SALE_COUNTER", "Sale — counter"),
                            ("SALE_ONLINE", "Sale — online"),
                            ("CUT_FROM_ROLL", "Cut from roll (remnant created)"),
                            ("CUSTOMER_RETURN", "Customer return"),
                            ("DAMAGE", "Damage / rejection"),
                            ("RTV", "Return to vendor"),
                            ("ONLINE_RESERVE", "Reserved for online order"),
                            ("ONLINE_RELEASE", "Online reservation released"),
                            ("STOCK_COUNT_ADJUSTMENT", "Physical count adjustment"),
                            ("STOCK_TRANSFER", "Transfer between locations"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "quantity_delta",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=64)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="laxmi_backend.sku",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to="laxmi_backend.staffuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="bill",
            name="cashier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bills",
                to="laxmi_backend.staffuser",
            ),
        ),
        migrations.AddIndex(
            model_name="sku",
            index=models.Index(
                fields=["sku_code"], name="laxmi_backe_sku_cod_84379a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sku",
            index=models.Index(
                fields=["barcode"], name="laxmi_backe_barcode_427333_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryledger",
            index=models.Index(
                fields=["sku", "created_at"], name="laxmi_backe_sku_id_f57c1a_idx"
            ),
        ),
    ]
